# Generated by Django 3.2.8 on 2021-11-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cantact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
